### ISSUE TITLE
[feature request] change icon depending on connection state

### ISSUE THREAD

**Issue by jtl5770** [SJBERTRAND/gnome-wireguard-extension#1]
It would be nice, if the icon of the extension would e.g. be desaturated when no connection is active and fully colored as it is now when any connection is active (or any other means to quickly, visually differentiate between the two states)

**Comment by SJBERTRAND** [comment]
Done. I changed the Wireguard icon for the VPN enable/disable icons. Let me know if you have any issues. I will update the extension on gnome-extension later today.

**Comment by jtl5770** [comment]
To be honest, I would rather prefer to use this or similar:

![wireguard-disabled-icon](https://user-images.githubusercontent.com/24967370/194672778-fe76f96e-c50c-47ac-8cc8-aee71600049d.svg)

as the disabled icon than the generic vpn icons used because this may be misleading as they are used and shown elsewhere in the shell (whenever you use another VPN)

**Comment by SJBERTRAND** [comment]
Ok I added a folder name Version with WireGuard icon you can either download the content of the folder or the zip file in the folder. Not sure which one I prefer yet.
