### ISSUE TITLE
Error: Operation not permitted when starting interface

### ISSUE THREAD

**Issue by phifogg** [SJBERTRAND/gnome-wireguard-extension#13]
I setup a new debian gnome device, added this extention, imported my wireguard.conf file. So far all good.
When I try to start the connection, nothing works.

Error message as shown in wg show:

```
Unable to access interface <interface name>: Operation not permitted
```

I would assume this is due to me not doing the connection as root?

**Comment by phifogg** [comment]
Started debug of wireguard with 

```
$ echo "module wireguard +p" | sudo tee /sys/kernel/debug/dynamic_debug/control
```

Basically only one message in the logfile:

```
Sending handshake initiation to peer XX (ip)
```

Then nothing. I can ping the peer just fine.

**Comment by phifogg** [comment]
Just do add.. connection works fine from windows or android phone. just not from the debian system.

**Comment by SJBERTRAND** [comment]
Debian uses old libraries and Gnome 43. There was some changes on how to import API's in Gnome Java Script with Gnome 44. So for Debian you should download the extension version 11 for Gnome 43. It will use the proper API

![image](https://github.com/user-attachments/assets/35eef346-c50b-4cd0-938a-90456e367bdb)


I tried it in a VM on a fresh install of Debian stable and it worked without problem. I was able to import a config file an enable/disable the tunnel 

Let me know if it doesn't solve it.

**Comment by phifogg** [comment]
I tested it today again - this time from far far away :D This worked like charm.

Last time when I had issues was basically at home through my mobile phone's hot spot. Seems this is somehow connected to the hot spot.
