### ISSUE TITLE
Error when trying to install from extensions.gnome.org on Ubuntu 20.04.5

### ISSUE THREAD

**Issue by Chewie9999** [SJBERTRAND/gnome-wireguard-extension#2]
Should it work on this OS?
When I click on the "On" slider, I get the Install popup confirmation, and then I just get a red ERROR in the browser where it normally says ON if installation was successful.
Let me know if I can send any logs (not sure where they are)

Thanks!

**Comment by SJBERTRAND** [comment]
The extension was written for Gnome 42 and above.  Ubuntu 20.04 uses Gnome 3.36. There was a major changes in Gnome 40. I tried to used it in Ubuntu 20,04 and it doesn't work. It does work with Ubuntu 22.04. If I have time I may try to look what the issues can be.
