### ISSUE TITLE
Using wireguard icon instead of the generic

### ISSUE THREAD

**Issue by le-patenteux** [SJBERTRAND/gnome-wireguard-extension#3]
Hello, thank you for this amazing plugin, works right-out of the box!

I would like to suggest though, that you would change the icon for wireguard icons (gray when off, red when on)

I use several VPNs for work, and it would help differentiate them :)

Thank you

**Comment by SJBERTRAND** [comment]
Sorry for the late reply. I was away. I will update the extension on the gnome-extension website.

**Comment by SJBERTRAND** [comment]
Done. The version 6 is available from gnome-extension. It has the Wireguard icon that greys out when inactive. 
https://extensions.gnome.org/extension/5362/wireguard-vpn-extension/
Or you can download it from github. Just Download the zip file in the "Version with wireguard icons" folder and install it with the following command in a terminal.
$ gnome-extensions install gnome-wireguard-extension@SJBERTRAND.github.com.zip
Login and logout activate the extension and you should be good to go.
