### ISSUE TITLE
Extension can't find configs

### ISSUE THREAD

**Issue by TrueDru** [SJBERTRAND/gnome-wireguard-extension#4]
Hello, i just installed gnome-wireguard extension and i have 1 config in /etc/wireguard, but if i click on extension tray icon i only see "Connection Settings" button and if i click on it nothing happens.
My env:
OS: Manjaro Linux x86_64
DE: GNOME 43.2
WM: Mutter 
WM Theme: Adwaita
Thank you!

**Comment by SJBERTRAND** [comment]
Hi TrueDru

The extension used the netmorkmanager API  and need network-manager to run. You can check if network-manager is running with this command:

$ systemctl status NetworkManager.service

The extension only uses config file imported/created with nmcli (network manager client). Config file in /etc/wireguard requires root access to use and cannot be access with this extension. Extension that requires root access represent security risk and I would recommend avoiding them.

You can import a config file with nmcli using the following command (do not use sudo):

$ nmcli connection import type wireguard file <the path of the config file>

The "Connection Settings" button called the nm-connection-editor which should be install on your system but just in case open terminal and try to call the followin command. 

$ nm-connection-editor

On ArchLinux network-manager is installed by default when installing the gnome packages but I haven't try Manjaro. I'll install it in a VM and get back to you later.

**Comment by SJBERTRAND** [comment]
Update: (Just installed Manjaro) 

On Manjaro nm-connection-editor is not installed by default. You can install it with:

$ pacman -S nm-connection-editor

After that the "Connection Settings" button should work.

Let me know if you have more issues

**Comment by TrueDru** [comment]
Thank you! Fixed
