### ISSUE TITLE
Tunnel connects automatically at system start

### ISSUE THREAD

**Issue by nrgeen** [SJBERTRAND/gnome-wireguard-extension#6]
First of all, thank you very much for the great extension. I use it almost every day and I am happy about the ease of use.

In my daily use, however, I notice one negative point. As soon as I start the computer, my Wireguard tunnel connect automatically. I would like to deactivate this. Is that possible?

If so, I would like to have a switch with which I can set whether the tunnel should be set up automatically after system start-up or not.

**Comment by SJBERTRAND** [comment]
You can turn off the autoconnect in two different way.

You can use a gui call nm-connection-editor

You can start it from terminal with 

$ nm-connection-editor

You will see the wireguard tunnel in the bottom of the connections. Double click on the wireguard tunnel and in the General tab uncheck: connect automatically with priority


Other way is through the network-manager cli.

Open a terminal and type

$ nmcli connection modify <the name of your vpn tunnel> connection.autoconnect no

You can use tab to autofill.

Eventually I will try to have the extension disable autoconnect by default. Just not there yet.

**Comment by SJBERTRAND** [comment]
Sorry I missed something
nmcli connection modify name-of-your-wiregaurd-tunnel connection.autoconnect no

**Comment by SJBERTRAND** [comment]
Sorry this took a while but it been added. Wireguard connection when added from a configuration file using the extension will have autoconnect  enabled. It will autoconnect when you load the configuration file but will not autoconnect at system start.

Hope this help.

**Comment by SJBERTRAND** [comment]
Im waiting for the version 10 to be approved by gnome-extensions and it should be good.
