### ISSUE TITLE
Gnome 45 support / error

### ISSUE THREAD

**Issue by maxawake** [SJBERTRAND/gnome-wireguard-extension#8]
Hey! First of all thank you for that great plugin, nothing makes it as easy to setup a VPN client than this extension!

However, after upgrading to Gnome 45 the extension stopped working. I downloaded the recent version here from github which says "Version for Gnome 45" but i get an error  
```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  @file:///home/max/.local/share/gnome-shell/extensions/gnome-wireguard-extension@SJBERTRAND.github.com/prefs.js:5:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```
I am using Arch Linux 

Best regards, Max

**Comment by SJBERTRAND** [comment]
I only updated the metadta file right now to try it on gnome 45 but you are right is doesn't work. I'll do some investigation and try to fix it.

**Comment by maxawake** [comment]
I see, that explains a lot lol

I think the error might be related to gnome moving to ESM https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

In the best case it should be possible to fix everything by changing the import statements. If you have no time in the moment i can look into it as well

**Comment by maxawake** [comment]
So i made a fork of your project and changed the import statements here https://github.com/maxawake/gnome-wireguard-extension and as soon as everything works i would like to make a PR

I am now able to load the extension without crashing the gnome-shell and i am able to open the preferences dialog and change wireguard config files. However i still do not get the tray icon and option to enable / disable wireguard. 

The error i get with ALT + F2 "lg" is 
```
ambiguous indirect export: default
```

I am not really an expert in Javascript so i have no idea how to fix this issue. Maybe you can help?

**Comment by maxawake** [comment]
Nevermind i got it working. Can you test if this works for you on Gnome 45 as well? I created a pull request of the ported version of the extension here https://github.com/SJBERTRAND/gnome-wireguard-extension/pull/9 
Learned a bit JavaScript on the way!
